# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  test-rails:

    name: Rails Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['jruby-9.2.20.1']
        db: ['mysql2']
        test_targets: ["rails:test_mysql2"]
        ar_version: ["6-1-stable"]
        prepared_statements: ['false']
        driver: ['MySQL']

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        ports:
          - 3306

    env:
      DB: ${{ matrix.db }}
      TEST_PREFIX: ${{ matrix.test_prefix }}
      AR_VERSION: ${{ matrix.ar_version }}
      PREPARED_STATEMENTS: ${{ matrix.prepared_statements }}
      DRIVER: ${{ matrix.driver }}
      JRUBY_OPTS: "-J-Xms64M -J-Xmx1024M"

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Setup database
        run: |
          sudo service mysql start
          mysql --version || true # to see if we're using MySQL or MariaDB
          mysql -u root -proot -e "CREATE USER rails@localhost;"
          mysql -u root -proot -e "grant all privileges on activerecord_unittest.* to rails@localhost;"
          mysql -u root -proot -e "grant all privileges on activerecord_unittest2.* to rails@localhost;"
          mysql -u root -proot -e "grant all privileges on inexistent_activerecord_unittest.* to rails@localhost;"
          mysql -u root -proot -e "CREATE DATABASE activerecord_unittest DEFAULT CHARACTER SET utf8mb4;"
          mysql -u root -proot -e "CREATE DATABASE activerecord_unittest2 DEFAULT CHARACTER SET utf8mb4;"
      - name: Build
        run: |
          echo "JAVA_OPTS=$JAVA_OPTS"
          rake jar # compiles ext generates: lib/arjdbc/jdbc/adapter_java.jar
      - name: Run tests
        run: |
          bundle exec rake ${{ matrix.test_targets }}

  test-arjdbc-mysql:

    name: ARJDBC Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['jruby-9.2.20.1']
        db: ['mysql2']
        test_targets: ["db:mysql test_mysql2"]
        driver: ['MySQL']

    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306

    env:
      DB: ${{ matrix.db }}
      DRIVER: ${{ matrix.driver }}
      JRUBY_OPTS: "-J-Xms64M -J-Xmx1024M"
      MY_USER: root
      MY_PASSWORD: root

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Setup database
        run: |
          sudo service mysql start
          mysql --version || true # to see if we're using MySQL or MariaDB
      - name: Build
        run: |
          rake jar
      - name: Run tests
        run: |
          bundle exec rake ${{ matrix.test_targets }}

  test-arjdbc-sqlite:

    name: ARJDBC Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['jruby-9.2.20.1']
        db: ['sqlite3']
        test_targets: ['test_sqlite3']

    env:
      DB: ${{ matrix.db }}
      JRUBY_OPTS: "-J-Xms64M -J-Xmx1024M"

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Build
        run: |
          rake jar
      - name: Run tests
        run: |
          bundle exec rake ${{ matrix.test_targets }}